# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e78f2151fe83573efcb6ea942704d6171816150e630482b4c86b6ced2bd945a1533d3abfd316c2462e50ce1b0ca936bf86171f73c3c32c6c925f19c139398b38

test:
  secret_key_base: f905a9b6397b37538e9233e80c3c021a3c62805544537934159d034612aa3f3bbeea2e16aaa2c75685e8c73009e4c7a9dc0521c4cc78bcf18245efb89cade7ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
